workflows:
  android_apk_debug:
    name: Android APK (debug)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Prepare & deps
        script: |
          flutter --version
          flutter pub get
      - name: Fix android template (if needed)
        script: |
          # hapus settings.gradle.kts kalau ada
          [ -f android/settings.gradle.kts ] && rm android/settings.gradle.kts || true
          # regen template android agar Gradle valid
          flutter create . --platforms=android --overwrite
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
