workflows:
  android_apk_debug:
    name: Android APK (debug)
    max_build_duration: 60

    # Pindah ke Linux agar unduhan Flutter lebih stabil/cepat
    instance_type: linux_x2   # atau linux_x1 jika x2 tidak tersedia

    environment:
      # Pin versi Flutter biar tidak download “latest” setiap kali
      flutter: 3.24.3
      java: 17
      # Jika kamu berada di jaringan yang susah akses Google Storage,
      # kamu bisa aktifkan mirror ini (hapus tanda #):
      # FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
      # PUB_HOSTED_URL: https://pub.flutter-io.cn

    cache:
      cache_paths:
        - $CM_BUILD_DIR/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper

    scripts:
      - name: Prepare & deps
        script: |
          flutter --version
          flutter pub get

      - name: Regenerate clean Android folder
        script: |
          rm -rf android
          flutter create . --platforms=android

      - name: Build debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
