workflows:
  android_apk_debug:
    name: Android APK (debug)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17

    scripts:
      - name: Prepare & deps
        script: |
          flutter --version
          flutter pub get

      - name: Regenerate clean Android folder
        script: |
          # Hapus folder android lama agar tidak ada sisa konfigurasi yang bentrok
          rm -rf android
          # Buat ulang template Android sesuai versi Flutter di mesin build
          flutter create . --platforms=android

      - name: Build debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
