workflows:
  android_apk_debug:
    name: Android APK (debug)
    max_build_duration: 60
    # Pakai Linux agar cocok dengan paket gratis:
    instance_type: linux_x2   # boleh diganti "linux" jika x2 tidak ada
    environment:
      flutter: stable
      java: 17
      # Mirror opsional agar download Flutter/dep lebih stabil
      vars:
        PUB_HOSTED_URL: https://pub.flutter-io.cn
        FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn

    scripts:
      - name: Prepare & deps
        script: |
          flutter --version
          flutter pub get

      # (Opsional) hanya jika mau mereset template Android yang bikin error Gradle
      # - name: Regenerate clean Android folder
      #   script: |
      #     rm -f android/settings.gradle.kts || true
      #     rm -f android/settings.gradle || true
      #     flutter create . --platforms=android --overwrite

      - name: Build debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
