workflows:
  android_apk_debug:
    name: Android APK (debug)
    max_build_duration: 60
    instance_type: linux_x2        # pakai Linux (gratis). Kalau tidak ada, gunakan "linux"
    environment:
      flutter: stable
      java: 17
      # mirror opsional agar download lebih stabil
      vars:
        PUB_HOSTED_URL: https://pub.flutter-io.cn
        FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn

    scripts:
      - name: Prepare & deps
        script: |
          flutter --version
          flutter pub get

      - name: Regenerate clean Android folder (fix settings.gradle)
        script: |
          # buang file settings.gradle/settings.gradle.kts yang rusak
          rm -f android/settings.gradle || true
          rm -f android/settings.gradle.kts || true
          # optional: bersihkan cache gradle lokal project
          rm -rf android/.gradle || true
          # tulis ulang template Android sesuai versi Flutter di mesin build
          flutter create . --platforms=android --overwrite

      - name: Build debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
