workflows:
  android_apk_debug:
    name: Android APK (debug)
    max_build_duration: 60
    # Gunakan Linux agar tidak kena limit plan macOS
    instance_type: linux_x2

    environment:
      flutter: stable
      java: 17
      vars:
        # MIRROR opsional (punyamu sudah aktif; boleh hapus jika tidak perlu)
        FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
        PUB_HOSTED_URL: https://pub.flutter-io.cn

    scripts:
      - name: Prepare & deps
        script: |
          flutter --version
          flutter pub get

      - name: Regenerate clean Android folder (safe)
        script: |
          rm -f android/settings.gradle || true
          rm -f android/settings.gradle.kts || true
          rm -rf android/.gradle || true
          # Tidak pakai --overwrite => lib/ & pubspec.yaml aman
          flutter create . --platforms=android

      - name: Build debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
